source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'database'
cookbook 'git'
cookbook 'nodejs'
cookbook 'postgresql'
cookbook 'python'
cookbook 'city-hall-api',
  path: 'cookbooks/city-hall-api'
